/**
 * Finding the real database query inside a Power Query expression.
 *
 * A table's partition is almost always `type: "m"`, so showing "the source
 * query" as the whole M script is not what a report author means by SQL. The
 * actual statement, when there is one, sits inside the M as a string argument
 * to a connector — `Sql.Database(.., [Query="SELECT .."])`,
 * `Value.NativeQuery(src, "SELECT ..")`, `Odbc.Query(conn, "SELECT ..")` and
 * friends.
 *
 * This module locates that string and records its exact offsets, so the SQL can
 * be shown on its own and edited back into the M without disturbing anything
 * around it.
 *
 * When no native statement exists the query is being generated by query
 * folding, which happens inside the mashup engine and is not present in the
 * file at all. That case reports why rather than inventing a statement.
 */

export type TokenKind = "string" | "identifier" | "punct" | "other";

export interface MToken {
  kind: TokenKind;
  /** For strings: the decoded value. Otherwise the raw text. */
  value: string;
  /** Offsets into the original expression, covering the whole token. */
  start: number;
  end: number;
}

/**
 * M string escapes.
 *
 * A quote is doubled, and control characters use `#(lf)`, `#(cr)`, `#(tab)`,
 * with `#(#)` for a literal hash. Power BI writes multi-line SQL with `#(lf)`
 * rather than real newlines, so decoding these is what turns a single
 * unreadable line into the statement the author actually wrote.
 */
const M_ESCAPES: Record<string, string> = {
  lf: "\n",
  cr: "\r",
  tab: "\t",
  "#": "#",
};

const decodeMString = (raw: string) =>
  raw
    .slice(1, -1)
    .replace(/""/g, '"')
    .replace(/#\((lf|cr|tab|#)\)/g, (match, code: string) => M_ESCAPES[code] ?? match);

export const encodeMString = (value: string) =>
  `"${value
    // The hash goes first, or the escapes written below get escaped again.
    .replace(/#/g, "#(#)")
    .replace(/"/g, '""')
    .replace(/\r/g, "#(cr)")
    .replace(/\n/g, "#(lf)")
    .replace(/\t/g, "#(tab)")}"`;

/**
 * Tokenize far enough to tell strings, comments and identifiers apart. This is
 * not a full M parser; it exists so that a `Query=` sitting inside a comment or
 * another string can never be mistaken for the real one.
 */
export function tokenizeM(expression: string): MToken[] {
  const tokens: MToken[] = [];
  let i = 0;

  while (i < expression.length) {
    const char = expression[i];

    if (/\s/.test(char)) {
      i++;
      continue;
    }

    if (expression.startsWith("//", i)) {
      while (i < expression.length && expression[i] !== "\n") i++;
      continue;
    }

    if (expression.startsWith("/*", i)) {
      const close = expression.indexOf("*/", i + 2);
      i = close === -1 ? expression.length : close + 2;
      continue;
    }

    // `#"Quoted Name"` is an escaped identifier, not a string.
    if (expression.startsWith('#"', i)) {
      let j = i + 2;
      while (j < expression.length) {
        if (expression[j] === '"') {
          if (expression[j + 1] === '"') j += 2;
          else break;
        } else j++;
      }
      tokens.push({ kind: "identifier", value: expression.slice(i, j + 1), start: i, end: j + 1 });
      i = j + 1;
      continue;
    }

    if (char === '"') {
      let j = i + 1;
      while (j < expression.length) {
        if (expression[j] === '"') {
          if (expression[j + 1] === '"') j += 2;
          else break;
        } else j++;
      }
      const end = Math.min(j + 1, expression.length);
      tokens.push({
        kind: "string",
        value: decodeMString(expression.slice(i, end)),
        start: i,
        end,
      });
      i = end;
      continue;
    }

    const identifier = /^[A-Za-z_][\w.]*/.exec(expression.slice(i));
    if (identifier) {
      tokens.push({
        kind: "identifier",
        value: identifier[0],
        start: i,
        end: i + identifier[0].length,
      });
      i += identifier[0].length;
      continue;
    }

    tokens.push({ kind: "punct", value: char, start: i, end: i + 1 });
    i++;
  }

  return tokens;
}

/**
 * Connectors whose second positional argument is the statement.
 * `Value.NativeQuery(source, "SELECT ...", ...)`.
 */
const SECOND_ARG_CONNECTORS = new Set([
  "Value.NativeQuery",
  "Odbc.Query",
  "OleDb.Query",
]);

/**
 * Connectors that take the statement in a `[Query="..."]` option record. The
 * record may be the second, third or fourth argument depending on connector,
 * so the record is searched rather than a fixed position.
 */
const QUERY_OPTION_CONNECTORS = new Set([
  "Sql.Database",
  "Oracle.Database",
  "PostgreSQL.Database",
  "MySQL.Database",
  "Teradata.Database",
  "AmazonRedshift.Database",
  "Db2.Database",
  "Informix.Database",
  "SapHana.Database",
  "Snowflake.Databases",
  "GoogleBigQuery.Database",
  "Vertica.Database",
  "Sybase.Database",
]);

/** Connectors that reach a relational source but fold rather than carry SQL. */
const FOLDING_CONNECTORS = new Set([
  ...QUERY_OPTION_CONNECTORS,
  "Sql.Databases",
  "Odbc.DataSource",
  "OleDb.DataSource",
]);

export interface NativeQuery {
  /** The statement itself, already unescaped. */
  sql: string;
  /** Which connector supplied it, for display. */
  connector: string;
  /** Offsets of the string literal in the M, including its quotes. */
  start: number;
  end: number;
}

export type NativeQueryResult =
  | { kind: "native"; query: NativeQuery }
  | { kind: "folded"; connector: string; reason: string }
  | { kind: "none"; reason: string };

/** Index of the matching close paren for the `(` at `open`. */
function matchParen(tokens: MToken[], open: number): number {
  let depth = 0;
  for (let i = open; i < tokens.length; i++) {
    if (tokens[i].kind !== "punct") continue;
    if (tokens[i].value === "(") depth++;
    else if (tokens[i].value === ")") {
      depth--;
      if (depth === 0) return i;
    }
  }
  return -1;
}

/** The first string literal that is a direct argument at argument position n. */
function positionalString(tokens: MToken[], open: number, close: number, position: number) {
  let depth = 0;
  let argument = 0;
  for (let i = open; i < close; i++) {
    const token = tokens[i];
    if (token.kind === "punct") {
      if (token.value === "(" || token.value === "[" || token.value === "{") depth++;
      else if (token.value === ")" || token.value === "]" || token.value === "}") depth--;
      else if (token.value === "," && depth === 1) argument++;
      continue;
    }
    // Only a token sitting directly inside the call counts as that argument.
    if (depth === 1 && argument === position && token.kind === "string") return token;
  }
  return undefined;
}

/** A `Query = "..."` field anywhere inside the call's option record. */
function queryOptionString(tokens: MToken[], open: number, close: number) {
  for (let i = open; i < close - 2; i++) {
    if (tokens[i].kind !== "identifier") continue;
    if (tokens[i].value !== "Query" && tokens[i].value !== '#"Query"') continue;
    const equals = tokens[i + 1];
    const value = tokens[i + 2];
    if (equals?.kind === "punct" && equals.value === "=" && value?.kind === "string") return value;
  }
  return undefined;
}

/**
 * The native statement inside an M expression, or an explanation of why there
 * is not one. Never returns a fabricated query.
 */
export function findNativeQuery(expression: string): NativeQueryResult {
  if (!expression.trim()) {
    return { kind: "none", reason: "This partition has no source expression." };
  }

  const tokens = tokenizeM(expression);
  let foldingConnector: string | undefined;

  for (let i = 0; i < tokens.length; i++) {
    const token = tokens[i];
    if (token.kind !== "identifier") continue;

    const next = tokens[i + 1];
    if (!next || next.kind !== "punct" || next.value !== "(") continue;

    const close = matchParen(tokens, i + 1);
    if (close === -1) continue;

    if (SECOND_ARG_CONNECTORS.has(token.value)) {
      const statement = positionalString(tokens, i + 1, close, 1);
      if (statement) {
        return {
          kind: "native",
          query: {
            sql: statement.value,
            connector: token.value,
            start: statement.start,
            end: statement.end,
          },
        };
      }
    }

    if (QUERY_OPTION_CONNECTORS.has(token.value)) {
      const statement = queryOptionString(tokens, i + 1, close);
      if (statement) {
        return {
          kind: "native",
          query: {
            sql: statement.value,
            connector: token.value,
            start: statement.start,
            end: statement.end,
          },
        };
      }
    }

    if (FOLDING_CONNECTORS.has(token.value)) foldingConnector = token.value;
  }

  if (foldingConnector) {
    return {
      kind: "folded",
      connector: foldingConnector,
      reason: `This table reaches a relational source through ${foldingConnector}, but no SQL statement is written in the file. Power Query builds the statement at refresh time by folding the transformation steps, and that generated SQL exists only inside the mashup engine. Power BI Desktop can show it through "View Native Query" on the last folded step.`,
    };
  }

  return {
    kind: "none",
    reason:
      "No relational connector was found in this table's source, so there is no database query behind it. It may be loaded from a file, a folder, an API, or entered directly.",
  };
}

/**
 * Put an edited statement back into the M expression, replacing only the string
 * literal and leaving every other character untouched.
 */
export function replaceNativeQuery(expression: string, sql: string): string | undefined {
  const found = findNativeQuery(expression);
  if (found.kind !== "native") return undefined;
  return (
    expression.slice(0, found.query.start) +
    encodeMString(sql) +
    expression.slice(found.query.end)
  );
}
